//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public int cid { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string time_deadline { get; set; }
        public string submission_date { get; set; }
        public string desc { get; set; }
        public byte[] file_url { get; set; }
        public string heading { get; set; }
        public System.DateTime create_date { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
