//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Activities = new HashSet<Activity>();
            this.Enrollments = new HashSet<Enrollment>();
            this.Requests = new HashSet<Request>();
        }
    
        public int Id { get; set; }
        public int instructor { get; set; }
        public string name { get; set; }
        public string institution { get; set; }
        public string dept { get; set; }
        public string desc { get; set; }
        public System.DateTime created { get; set; }
    
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
    }
}
