//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Classes = new HashSet<Class>();
            this.Comments = new HashSet<Comment>();
            this.Enrollments = new HashSet<Enrollment>();
            this.Requests = new HashSet<Request>();
        }
    
        public int Id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string type { get; set; }
        public string password { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<Class> Classes { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
    }
}
